version: '3.1'
services:
  db:
    #image: thedifferent/mariadb
    build: mariadb/gina
    environment:
      - "MYSQL_ROOT_HOST=localhost"
      - "MYSQL_ROOT_PASSWORD=ciscocisco"
      - "MYSQL_ROOT_PASSWORD_LOCAL=false"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wp"
      - "MYSQL_PASSWORD=cisco"

  wordpress:
    image: thedifferent/wordpress-alpine
    #build: wordpress/novolume
    depends_on:
      - "db"
    ports:
      - "80:80"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=wordpress"
      - "DB_USER=wp"
      - "DB_PASSWORD=cisco"
      - "WORDPRESS_SITE_URL=http://localhost"
